### ISSUE TITLE
Continues to crash on open of theater movies window 

### ISSUE THREAD

**Issue by newscientist101** [logbon72/pebble-movies#2]
More often than not app crashes before it can display movies at a specific theater.

**Comment by logbon72** [comment]
Please provide firmware version, and location details (country, city & postal code) so I can replicate the issue.

Thanks

**Comment by newscientist101** [comment]
Firmware: Pebble Time 3.8
Location: USA, Crystal Lake, 60012

**Comment by logbon72** [comment]
Hello,

This issue has been resolved. It was due to a disparity between string length and the actual byte size of the data being sent to the watch for non-ASCII characters.

**Comment by logbon72** [comment]
Fixed by https://github.com/logbon72/pebble-movies/commit/23776961c05847217baa11039a9365e71ab9ba57

**Comment by logbon72** [comment]
Fixed by https://github.com/logbon72/pebble-movies/commit/23776961c05847217baa11039a9365e71ab9ba57
